export const GET_DEFINITIONS = 'GET_DEFINITIONS';
export const SET_DEFINITIONS = 'SET_DEFINITIONS';
export const BOOK_LOADED = 'BOOK_LOADED';
export const EVENTS_LOADED = 'EVENTS_LOADED';
export const RESET_READER = 'RESET_READER';
export const SET_IDENTIFIER = 'SET_IDENTIFIER';
export const SET_LOCATION = 'SET_LOCATION';
